# Generated by Django 5.1 on 2024-11-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=255)),
                ('Direccion', models.TextField()),
            ],
        ),
    ]
