# Generated by Django 5.1 on 2024-11-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ID_Cliente',
            new_name='id_cliente',
        ),
    ]
