# Generated by Django 5.1 on 2024-11-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0002_rename_id_cliente_cliente_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='F_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
